### ISSUE TITLE
Question: Is it possible to use .renderEmojis and .renderFont in canvacord.Welcomer()

### ISSUE THREAD

**Issue by rssan0307** [DevAndromeda/canvacord#122]
For my discord bot I require emojis to be rendered and fonts to be rendered for the welcoming image. And it says that .renderEmojijs() is not a function. Is there any work around this? 

Btw both these functions work when making a rank card.

**Comment by DevAndromeda** [comment]
It should render emojis via system fonts from v5.4.0 (you can try installing some fonts on your system or load it via canvacord manually)
