### ISSUE TITLE
Level

### ISSUE THREAD

**Issue by thoriqazzikraa** [DevAndromeda/canvacord#123]
![IMG-20220531-WA0102.jpg](https://user-images.githubusercontent.com/89589243/171122082-837484b4-66e2-4a17-9ca7-b6d17ac5091c.jpg)

As you can see, bug on level number

**Comment by FabienBounoir** [comment]
I have the same bug, I rollback to 5.2.3v

**Comment by DevAndromeda** [comment]
use v5.4.0
