### ISSUE TITLE
cannot install canvacord package

### ISSUE THREAD

**Issue by imia307** [DevAndromeda/canvacord#127]
![image](https://user-images.githubusercontent.com/79816488/174247089-b0e14486-1f4f-4b70-8ac2-dd0c5741d37e.png)

When I try install canvacord I get this error

PS C:\Users\GGPC\Desktop\Tester bot> npm install canvacord
npm ERR! code 1
npm ERR! path C:\Users\GGPC\Desktop\Tester bot\node_modules\canvas
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\GGPC\Desktop\Tester bot\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\GGPC\Desktop\Tester bot\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.9
npm ERR! node-pre-gyp info using node@18.4.0 | win32 | x64
npm ERR! node-pre-gyp info check checked for "C:\Users\GGPC\Desktop\Tester bot\node_modules\canvas\build\Release\canvas.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-node-v108-win32-unknown-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-node-v108-win32-unknown-x64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.9.1 and node@18.4.0 (node-v108 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-node-v108-win32-unknown-x64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@18.4.0 | win32 | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@18.4.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.2 found at "C:\Users\GGPC\AppData\Local\Programs\Python\Python310\python.exe"
npm ERR! gyp http GET https://nodejs.org/download/release/v18.4.0/node-v18.4.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v18.4.0/node-v18.4.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v18.4.0/SHASUMS256.txt
npm ERR! gyp http GET https://nodejs.org/download/release/v18.4.0/win-x86/node.lib
npm ERR! gyp http GET https://nodejs.org/download/release/v18.4.0/win-x64/node.lib
npm ERR! gyp http GET https://nodejs.org/download/release/v18.4.0/win-arm64/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v18.4.0/SHASUMS256.txt
npm ERR! gyp http 404 https://nodejs.org/download/release/v18.4.0/win-arm64/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v18.4.0/win-x86/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v18.4.0/win-x64/node.lib
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\GGPC\Desktop\Tester bot\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\GGPC\Desktop\Tester bot\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\GGPC\Desktop\Tester bot\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:537:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.22000
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\GGPC\\Desktop\\Tester bot\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd C:\Users\GGPC\Desktop\Tester bot\node_modules\canvas
npm ERR! node-pre-gyp ERR! node -v v18.4.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.9
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\GGPC\AppData\Local\npm-cache\_logs\2022-06-17T07_13_27_069Z-debug-0.log
PS C:\Users\GGPC\Desktop\Tester bot>

**Comment by DevAndromeda** [comment]
Hello, you are missing the build tools required to install native node modules.
Since canvas is a native module, you wont be able to install it unless you have build tools installed.

In order to install build tools, please go to https://nodejs.org and download a node.js installer. After that, you can run the installer and **MAKE SURE TO CHECK THIS OPTION** while installing:
![image](https://user-images.githubusercontent.com/46562212/174427796-280c513c-7b5b-45fe-a4dc-61b391ec6cf3.png)

after that, you should be good to go

**Comment by imia307** [comment]
I did this but im still encountering errors?
[image: image.png]
