### ISSUE TITLE
>= v5.4.0 have problem with @napi-rs/canvas on aarch64

### ISSUE THREAD

**Issue by LWJerri** [DevAndromeda/canvacord#132]
https://github.com/Brooooooklyn/canvas/issues/507

**Comment by DevAndromeda** [comment]
We dont have control over napi-rs/canvas

It should work fine if the canvas lib we are depending upon works on your system

**Comment by LWJerri** [comment]
> We dont have control over napi-rs/canvas
> 
> It should work fine if the canvas lib we are depending upon works on your system

Helo. I just create this issue. because some people can get this error, the author of napi-rc/canvas fix it next week.

**Comment by LWJerri** [comment]
@DevAndromeda, can you bump @napi-rc/canvas to latest version? Developer fixed problem with package installing on aarch64.

**Comment by DevAndromeda** [comment]
done in https://github.com/DevAndromeda/canvacord/releases/tag/v5.4.4
