### ISSUE TITLE
[Bug]: Font style and emoji support questions.

### ISSUE THREAD

**Issue by LWJerri** [DevAndromeda/canvacord#136]
Minimal code to reproduce the problem:
```ts
await new Rank()
// some other configs params...
.renderEmojis(true)
.build({ fontX: "Arial", fontY: "Arial" });

// I have the latest package version.
```

Screenshot:
![image](https://user-images.githubusercontent.com/50290430/183749185-5b0b8a6a-4f2e-4e52-9df7-97321740628a.png)
![image](https://user-images.githubusercontent.com/50290430/183749207-2b747fab-1e97-48a3-ab16-c21cc35f3baf.png)

**Comment by DevAndromeda** [comment]
> Minimal code to reproduce the problem:
> 
> ```ts
> await new Rank()
> // some other configs params...
> .renderEmojis(true)
> .build({ fontX: "Arial", fontY: "Arial" });
> 
> // I have the latest package version.
> ```
> 
> Screenshot: ![image](https://user-images.githubusercontent.com/50290430/183749185-5b0b8a6a-4f2e-4e52-9df7-97321740628a.png) ![image](https://user-images.githubusercontent.com/50290430/183749207-2b747fab-1e97-48a3-ab16-c21cc35f3baf.png)

Wdym by the font style? You set it to arial :thinking:

**Comment by DevAndromeda** [comment]
And yes, `.renderEmojis` was removed, it basically does nothing in the latest version. It exists for backwards compatibility (only in terms of API)

**Comment by LWJerri** [comment]
Okay, I'm removed `{ fontX: "Arial", fontY: "Arial" }` from `build()` and `.renderEmojis(true)`, but emojis don't rendered :(

**Comment by DevAndromeda** [comment]
> Okay, I'm removed `{ fontX: "Arial", fontY: "Arial" }` from `build()` and `.renderEmojis(true)`, but emojis don't rendered :(

Yeah, that's because there is no font available that accepts unicode characters. Which system are you on? On windows, it uses windows' font to render emoji and same goes on mac. You can try installing a font like apple emoji or something similar on your system and see if it works. Canvacord currently does not bundle emoji font

**Comment by LWJerri** [comment]
> > Okay, I'm removed `{ fontX: "Arial", fontY: "Arial" }` from `build()` and `.renderEmojis(true)`, but emojis don't rendered :(
> 
> Yeah, that's because there is no font available that accepts unicode characters. Which system are you on? On windows, it uses windows' font to render emoji and same goes on mac. You can try installing a font like apple emoji or something similar on your system and see if it works. Canvacord currently does not bundle emoji font

I'm using Ubuntu 22.04 LTS on aarch64 architecture.

**Comment by DevAndromeda** [comment]
ref https://github.com/Brooooooklyn/canvas/issues/511

**Comment by Brooooooklyn** [comment]
For reference: https://github.com/Brooooooklyn/canvas/issues/511#issuecomment-1214356011

**Comment by LWJerri** [comment]
@DevAndromeda, I need to install the font and write the font name in `.build()` as `fontX` or `fontY`, yes?

**Comment by DevAndromeda** [comment]
@LWJerri that could also work but im thinking about implementing it via `.renderEmojis` method

**Comment by DevAndromeda** [comment]
I will do it today

**Comment by LWJerri** [comment]
Okay.

**Comment by DevAndromeda** [comment]
[v5.4.6](https://github.com/DevAndromeda/canvacord/releases/tag/v5.4.6)
